### ISSUE TITLE
[Feature plan] [Customize property] changing names of numeric points

### ISSUE THREAD

**Issue by sandsieve** [lanyanxiang/habits-cli#15]
In the future update, the new feature of customizing property will be introduced.
The users will be able to change the name of their points into personalized usage, for example CAD, USD, Study Token etc.
However, the default name "points" will still be there and if the user does not want to specify the name of their numeric points, the points will be automatically named as points.
The user will also be able to store multiple groups of numeric points with different names in their property.

**Comment by lanyanxiang** [comment]
Wow, that was a lot of issues.

Thanks for the suggestions, all kinds of feedback are appreciated.

However, I know we sort of mentioned this via Zoom meeting, but since this is an issue, let's follow the syntax of an issue (rather than the release plan). Things in an issue may or may not be delivered. i.e., I need to see if I got some time to code this, or if someone else creates a pull request for things, we also need to find time to review their code.

Can you edit the message? 😀

**Comment by lanyanxiang** [comment]
Actually, upon further reading, I just realize that I implemented this in another branch yesterday. Sorry for the late information. Closing this ticket.

**Comment by lanyanxiang** [comment]
This was in the release plan: https://github.com/lanyanxiang/habits-cli/blob/develop/docs/release-plans/v0.2.md#features-from-timeline-planning-for-v02
