### ISSUE TITLE
[Feature Plan][Customize Property] Decimal number handling

### ISSUE THREAD

**Issue by sandsieve** [lanyanxiang/habits-cli#16]
For all the numeric points, the app will be able to handle decimal input, output and storage.
I think that the users should also be able to set the decimal handling based on their need for certain defined objects. They can choose to let the certain object only handle integers and can also increase the number of decimals the certain object handles.
By default, all the numeric object will handle 2 decimal numbers.

**Comment by lanyanxiang** [comment]
Wow, that was a lot of issues.

Thanks for the suggestions, all kinds of feedback are appreciated.

However, I know we sort of mentioned this via Zoom meeting, but since this is an issue, let's follow the syntax of an issue (rather than the release plan). Things in an issue may or may not be delivered. i.e., I need to see if I got some time to code this, or if someone else creates a pull request for things, we also need to find time to review their code.

Can you edit the message? 😀

**Comment by lanyanxiang** [comment]
Do you mean this section of the release plan? https://github.com/lanyanxiang/habits-cli/blob/develop/docs/release-plans/v0.2.md#feature-requests-for-v02

**Comment by lanyanxiang** [comment]
We fixed the issue with floating-point numbers from v0.1. For custom properties, I think we probably don't need the user to specify decimal points - it's just a numerical value and they can use it however they want. We're not sure if allowing custom decimal-place validation would be a commonly needed feature, so closing this for now. We can definitely reopen or create a new issue if we realize this is needed. Thank you for creating the issue!
