### ISSUE TITLE
[Feature Plan][Customize Property] Storing string objects

### ISSUE THREAD

**Issue by sandsieve** [lanyanxiang/habits-cli#18]
Apart from numeric points, the user should also be able to store "objects" and "consumables" in the form of a string.
The object will require a name and a description of effect. They can also stack together if the user has multiple consumables with the same name and effect.
The consumables should disappear upon using and will take effect as its description.
Consumables should be introduced as an exclusive reward the user set for themselves and can be obtained when the user finishes all weekly missions/ gets an achievement/ purchases from the shop or all the other scenarios the user choose to add.
The purchase, mission reward and achievement option should be set as default way of getting consumables and can be modified by the user.

**Comment by lanyanxiang** [comment]
Wow, that was a lot of issues.

Thanks for the suggestions, all kinds of feedback are appreciated.

However, I know we sort of mentioned this via Zoom meeting, but since this is an issue, let's follow the syntax of an issue (rather than the release plan). Things in an issue may or may not be delivered. i.e., I need to see if I got some time to code this, or if someone else creates a pull request for things, we also need to find time to review their code.

Can you edit the message? 😀

**Comment by lanyanxiang** [comment]
Actually, after some thought, I think this feature can be achieved by numeric custom properties.

I mean, just declare the consumerable as a property.

**Comment by lanyanxiang** [comment]
This ticket is a bit stale and the feature should have been implemented to some extent. Therefore, I'll close this ticket for now. Please reopen if you have any additional questions/concerns! 😀
